[2023-04-21 11:06:50,825] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: First_DAG.bash_tash_delete_file manual__2023-04-21T11:06:47.820120+00:00 [queued]>
[2023-04-21 11:06:50,835] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: First_DAG.bash_tash_delete_file manual__2023-04-21T11:06:47.820120+00:00 [queued]>
[2023-04-21 11:06:50,836] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-21 11:06:50,837] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-21 11:06:50,837] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-21 11:06:50,851] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): bash_tash_delete_file> on 2023-04-21 11:06:47.820120+00:00
[2023-04-21 11:06:50,854] {standard_task_runner.py:52} INFO - Started process 922 to run task
[2023-04-21 11:06:50,857] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'First_DAG', 'bash_tash_delete_file', 'manual__2023-04-21T11:06:47.820120+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmpnsny2fz_', '--error-file', '/tmp/tmpyxsu3sph']
[2023-04-21 11:06:50,857] {standard_task_runner.py:80} INFO - Job 16: Subtask bash_tash_delete_file
[2023-04-21 11:06:50,903] {task_command.py:369} INFO - Running <TaskInstance: First_DAG.bash_tash_delete_file manual__2023-04-21T11:06:47.820120+00:00 [running]> on host 7b4a1553b0dc
[2023-04-21 11:06:50,965] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=First_DAG
AIRFLOW_CTX_TASK_ID=bash_tash_delete_file
AIRFLOW_CTX_EXECUTION_DATE=2023-04-21T11:06:47.820120+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-21T11:06:47.820120+00:00
[2023-04-21 11:06:50,967] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-04-21 11:06:50,968] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm /opt/***/data/DATA_CENTER/DATA_LAKE/dataset_raw.txt']
[2023-04-21 11:06:50,975] {subprocess.py:85} INFO - Output:
[2023-04-21 11:06:50,985] {subprocess.py:96} INFO - Command exited with return code 0
[2023-04-21 11:06:51,012] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=First_DAG, task_id=bash_tash_delete_file, execution_date=20230421T110647, start_date=20230421T110650, end_date=20230421T110651
[2023-04-21 11:06:51,030] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-21 11:06:51,062] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
